# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Create app directory
WORKDIR /app

# Copy package files
COPY package.json package-lock.json* ./

# Install dependencies
RUN npm install --ignore-scripts

# Copy remaining source code
COPY . .

# Build the project
RUN npm run build

EXPOSE 3000

# Start the server
CMD [ "npm", "start" ]
